---
title: "longMI: Example Using the longMI Package"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Millsap-2011
  @Osborne-Suddick-1972
vignette: >
  %\VignetteIndexEntry{longMI: Example Using the longMI Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This is a reproduction of the example in https://quantdev.ssri.psu.edu/tutorials/intro-basics-longitudinal-measurement-invariance
using the `longMI` package.


```r
library(longMI)
```




```r
df <- longMI::osbornesudick1972
```


```r
head(df)
#>   id   y1_1   y1_2   y1_3   y1_4   y6_1   y6_2   y6_3   y6_4
#> 1  1 31.287 25.627 22.932 22.215 69.883 44.424 68.045 51.162
#> 2  2 13.801 14.787  7.581 15.373 41.871 44.862 33.897 37.741
#> 3  3 34.970 34.675 28.052 26.841 60.424 50.260 35.844 55.477
#> 4  4 24.795 31.391  8.208 20.197 52.865 42.669 45.802 35.987
#> 5  5 25.263 30.263 15.977 35.417 67.368 86.654 72.368 60.417
#> 6  6 15.402 23.399 11.453 20.560 46.437 52.956 22.537 47.716
```

## Data

The package assumes that the data is in the wide format
and the variables are named as follows:
`paste0("y", time_point, "_", item_number)`.
For example, for the item 1 from the first time point,
the variable name should be `y1_1`.
The data set has two time points (1 and 6).
There is a single factor with items 1, 2, 3, and 4 as indicators.
The four items correspond to the information (`y1_1` and `y6_1`),
comprehension (`y1_2` and `y6_2`),
similarities (`y1_3` and `y6_3`), and
vocabulary (`y1_4` and `y6_4`)
components of the Wechsler Intelligence Scale for Children
[@Osborne-Suddick-1972].
We can use this information to specify the funtion arguments to be used later
as follows:


```r
time_points <- c(1, 6)
factor_loadings <- list(
  c(1, 2, 3, 4)
)
```

## Invariance

The `Invariance()` function can be used to fit the different longitudinal measurement invariance models
(configural, weak, strong, and strict invariance models).


```r
mi <- Invariance(
  data = df,
  time_points,
  factor_loadings,
  mimic = "mplus"
)
```

PERHAPS WE CAN MAKE METHODS TO SIMPLIFY THE OUTPUT.


```r
mi$fit_measures
#>                                 configural          weak        strong
#> npar                          2.500000e+01  2.200000e+01  1.900000e+01
#> fmin                          6.364765e-02  1.026893e-01  1.316735e-01
#> chisq                         2.596824e+01  4.189725e+01  5.372281e+01
#> df                            1.900000e+01  2.200000e+01  2.500000e+01
#> pvalue                        1.310764e-01  6.432407e-03  7.216997e-04
#> baseline.chisq                8.477405e+02  8.477405e+02  8.477405e+02
#> baseline.df                   2.800000e+01  2.800000e+01  2.800000e+01
#> baseline.pvalue               0.000000e+00  0.000000e+00  0.000000e+00
#> cfi                           9.914995e-01  9.757274e-01  9.649611e-01
#> tli                           9.874729e-01  9.691076e-01  9.607564e-01
#> cfi.robust                    9.914995e-01  9.757274e-01  9.649611e-01
#> tli.robust                    9.874729e-01  9.691076e-01  9.607564e-01
#> nnfi                          9.874729e-01  9.691076e-01  9.607564e-01
#> rfi                           9.548577e-01  9.370989e-01  9.290236e-01
#> nfi                           9.693677e-01  9.505777e-01  9.366282e-01
#> pnfi                          6.577852e-01  7.468825e-01  8.362752e-01
#> ifi                           9.915918e-01  9.759037e-01  9.650889e-01
#> rni                           9.914995e-01  9.757274e-01  9.649611e-01
#> nnfi.robust                   9.874729e-01  9.691076e-01  9.607564e-01
#> rni.robust                    9.914995e-01  9.757274e-01  9.649611e-01
#> logl                         -5.601115e+03 -5.609079e+03 -5.614992e+03
#> unrestricted.logl            -5.588131e+03 -5.588131e+03 -5.588131e+03
#> aic                           1.125223e+04  1.126216e+04  1.126798e+04
#> bic                           1.133518e+04  1.133516e+04  1.133103e+04
#> ntotal                        2.040000e+02  2.040000e+02  2.040000e+02
#> bic2                          1.125597e+04  1.126545e+04  1.127083e+04
#> rmsea                         4.240037e-02  6.658404e-02  7.504614e-02
#> rmsea.ci.lower                0.000000e+00  3.464774e-02  4.720491e-02
#> rmsea.ci.upper                7.945826e-02  9.696861e-02  1.027290e-01
#> rmsea.ci.level                9.000000e-01  9.000000e-01  9.000000e-01
#> rmsea.pvalue                  5.882580e-01  1.734975e-01  6.712191e-02
#> rmsea.close.h0                5.000000e-02  5.000000e-02  5.000000e-02
#> rmsea.notclose.pvalue         4.718752e-02  2.532922e-01  4.095424e-01
#> rmsea.notclose.h0             8.000000e-02  8.000000e-02  8.000000e-02
#> rmsea.robust                  4.240037e-02  6.658404e-02  7.504614e-02
#> rmsea.ci.lower.robust         0.000000e+00  3.464774e-02  4.720491e-02
#> rmsea.ci.upper.robust         7.945826e-02  9.696861e-02  1.027290e-01
#> rmsea.pvalue.robust           5.882580e-01  1.734975e-01  6.712191e-02
#> rmsea.notclose.pvalue.robust  4.718752e-02  2.532922e-01  4.095424e-01
#> rmr                           2.859752e+00  7.496699e+00  7.600600e+00
#> rmr_nomean                    3.161575e+00  8.287912e+00  8.401847e+00
#> srmr                          3.064127e-02  7.629877e-02  8.718366e-02
#> srmr_bentler                  3.064126e-02  7.202174e-02  8.589969e-02
#> srmr_bentler_nomean           3.387519e-02  7.962303e-02  9.429007e-02
#> crmr                          3.387520e-02  5.370899e-02  6.853573e-02
#> crmr_nomean                   3.841087e-02  6.090027e-02  7.664719e-02
#> srmr_mplus                    3.064127e-02  7.629877e-02  8.718366e-02
#> srmr_mplus_nomean             3.387520e-02  6.520903e-02  7.931397e-02
#> cn_05                         2.378000e+02  1.661799e+02  1.439766e+02
#> cn_01                         2.853064e+02  1.971711e+02  1.692726e+02
#> gfi                           9.946870e-01  9.913395e-01  9.890256e-01
#> agfi                          9.876963e-01  9.826790e-01  9.806851e-01
#> pgfi                          4.295239e-01  4.956698e-01  5.619464e-01
#> mfi                           9.830660e-01  9.524023e-01  9.320218e-01
#> ecvi                          3.723933e-01  4.210650e-01  4.496216e-01
#>                                     strict
#> npar                          1.500000e+01
#> fmin                          3.298018e-01
#> chisq                         1.345591e+02
#> df                            2.900000e+01
#> pvalue                        1.554312e-15
#> baseline.chisq                8.477405e+02
#> baseline.df                   2.800000e+01
#> baseline.pvalue               0.000000e+00
#> cfi                           8.712286e-01
#> tli                           8.756690e-01
#> cfi.robust                    8.712286e-01
#> tli.robust                    8.756690e-01
#> nnfi                          8.756690e-01
#> rfi                                     NA
#> nfi                                     NA
#> pnfi                          8.713187e-01
#> ifi                           8.710713e-01
#> rni                           8.712286e-01
#> nnfi.robust                   8.756690e-01
#> rni.robust                    8.712286e-01
#> logl                         -5.655410e+03
#> unrestricted.logl            -5.588131e+03
#> aic                           1.134082e+04
#> bic                           1.139059e+04
#> ntotal                        2.040000e+02
#> bic2                          1.134307e+04
#> rmsea                         1.335777e-01
#> rmsea.ci.lower                1.112465e-01
#> rmsea.ci.upper                1.567971e-01
#> rmsea.ci.level                9.000000e-01
#> rmsea.pvalue                  3.567812e-09
#> rmsea.close.h0                5.000000e-02
#> rmsea.notclose.pvalue         9.999344e-01
#> rmsea.notclose.h0             8.000000e-02
#> rmsea.robust                  1.335777e-01
#> rmsea.ci.lower.robust         1.112465e-01
#> rmsea.ci.upper.robust         1.567971e-01
#> rmsea.pvalue.robust           3.567812e-09
#> rmsea.notclose.pvalue.robust  9.999344e-01
#> rmr                           1.006330e+01
#> rmr_nomean                    1.112501e+01
#> srmr                          1.690386e-01
#> srmr_bentler                  1.328427e-01
#> srmr_bentler_nomean           1.465099e-01
#> crmr                          8.865701e-02
#> crmr_nomean                   9.986277e-02
#> srmr_mplus                    1.690386e-01
#> srmr_mplus_nomean             1.452372e-01
#> cn_05                         6.551901e+01
#> cn_01                         7.617832e+01
#> gfi                           9.759012e-01
#> agfi                          9.634363e-01
#> pgfi                          6.432076e-01
#> mfi                           7.720366e-01
#> ecvi                          8.066624e-01
```


```r
mi$difference
#> $`configural against weak`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)   
#> configural 19 11252 11335 25.968                                         
#> weak       22 11262 11335 41.897     15.929 0.14535       3   0.001173 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`configural against strong`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> configural 19 11252 11335 25.968                                          
#> strong     25 11268 11331 53.723     27.755 0.13332       6  0.0001045 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`configural against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> configural 19 11252 11335  25.968                                          
#> strict     29 11341 11391 134.559     108.59 0.21984      10  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`weak against strong`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)   
#> weak   22 11262 11335 41.897                                         
#> strong 25 11268 11331 53.723     11.826 0.12009       3   0.008005 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`weak against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> weak   22 11262 11335  41.897                                          
#> strict 29 11341 11391 134.559     92.662 0.24492       7  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`strong against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> strong 25 11268 11331  53.723                                          
#> strict 29 11341 11391 134.559     80.836 0.30686       4  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

## Fitting the Models One at a Time

The models can also be fitted one at a time using the
`Configural()`,
`Weak()`,
`Strong()`, and
`Strict()` functions.

### Model Fitting


```r
configural_fit <- Configural(
  data = df,
  time_points = time_points,
  factor_loadings = factor_loadings,
  mimic = "mplus"
)
lavaan::summary(configural_fit)
#> lavaan 0.6.16 ended normally after 75 iterations
#> 
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        27
#>   Number of equality constraints                     2
#> 
#>   Number of observations                           204
#>   Number of missing patterns                         1
#> 
#> Model Test User Model:
#>                                                       
#>   Test statistic                                25.968
#>   Degrees of freedom                                19
#>   P-value (Chi-square)                           0.131
#> 
#> Parameter Estimates:
#> 
#>   Standard errors                             Standard
#>   Information                                 Observed
#>   Observed information based on                Hessian
#> 
#> Latent Variables:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 =~                                             
#>     y1_1     (l11)    4.451    0.400   11.137    0.000
#>     y1_2              6.850    0.637   10.745    0.000
#>     y1_3              4.590    0.520    8.821    0.000
#>     y1_4              5.039    0.396   12.728    0.000
#>   t6f1 =~                                             
#>     y6_1     (l11)    4.451    0.400   11.137    0.000
#>     y6_2              4.006    0.489    8.194    0.000
#>     y6_3              4.551    0.545    8.346    0.000
#>     y6_4              4.102    0.453    9.057    0.000
#> 
#> Covariances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 ~~                                             
#>     t6f1              1.837    0.215    8.558    0.000
#> 
#> Intercepts:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1      (i1)   19.776    0.427   46.273    0.000
#>    .y1_2             21.797    0.680   32.036    0.000
#>    .y1_3             14.903    0.528   28.223    0.000
#>    .y1_4             20.396    0.439   46.416    0.000
#>    .y6_1      (i1)   19.776    0.427   46.273    0.000
#>    .y6_2             19.317    2.299    8.404    0.000
#>    .y6_3             11.922    2.516    4.738    0.000
#>    .y6_4             17.970    1.844    9.747    0.000
#>     t1f1              0.000                           
#>     t6f1              6.455    0.606   10.649    0.000
#> 
#> Variances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1             17.448    2.240    7.789    0.000
#>    .y1_2             47.511    5.754    8.257    0.000
#>    .y1_3             35.810    4.031    8.884    0.000
#>    .y1_4             13.999    2.133    6.563    0.000
#>    .y6_1             47.096    6.432    7.322    0.000
#>    .y6_2             73.850    8.388    8.805    0.000
#>    .y6_3             88.920   10.354    8.588    0.000
#>    .y6_4             23.267    4.182    5.564    0.000
#>     t1f1              1.000                           
#>     t6f1              5.834    1.167    4.997    0.000
weak_fit <- Weak(
  data = df,
  time_points = time_points,
  factor_loadings = factor_loadings,
  mimic = "mplus"
)
lavaan::summary(weak_fit)
#> lavaan 0.6.16 ended normally after 54 iterations
#> 
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        27
#>   Number of equality constraints                     5
#> 
#>   Number of observations                           204
#>   Number of missing patterns                         1
#> 
#> Model Test User Model:
#>                                                       
#>   Test statistic                                41.897
#>   Degrees of freedom                                22
#>   P-value (Chi-square)                           0.006
#> 
#> Parameter Estimates:
#> 
#>   Standard errors                             Standard
#>   Information                                 Observed
#>   Observed information based on                Hessian
#> 
#> Latent Variables:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 =~                                             
#>     y1_1     (l11)    4.933    0.339   14.562    0.000
#>     y1_2     (l12)    5.172    0.429   12.052    0.000
#>     y1_3     (l13)    5.072    0.397   12.762    0.000
#>     y1_4     (l14)    4.865    0.336   14.492    0.000
#>   t6f1 =~                                             
#>     y6_1     (l11)    4.933    0.339   14.562    0.000
#>     y6_2     (l12)    5.172    0.429   12.052    0.000
#>     y6_3     (l13)    5.072    0.397   12.762    0.000
#>     y6_4     (l14)    4.865    0.336   14.492    0.000
#> 
#> Covariances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 ~~                                             
#>     t6f1              1.558    0.136   11.439    0.000
#> 
#> Intercepts:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1      (i1)   19.776    0.445   44.430    0.000
#>    .y1_2             21.797    0.629   34.633    0.000
#>    .y1_3             14.903    0.544   27.411    0.000
#>    .y1_4             20.396    0.436   46.803    0.000
#>    .y6_1      (i1)   19.776    0.445   44.430    0.000
#>    .y6_2             15.049    2.299    6.547    0.000
#>    .y6_3             11.756    2.212    5.315    0.000
#>    .y6_4             16.111    1.765    9.130    0.000
#>     t1f1              0.000                           
#>     t6f1              5.824    0.429   13.591    0.000
#> 
#> Variances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1             16.079    2.188    7.349    0.000
#>    .y1_2             54.055    6.012    8.992    0.000
#>    .y1_3             34.578    3.941    8.775    0.000
#>    .y1_4             15.075    2.109    7.149    0.000
#>    .y6_1             49.748    6.494    7.661    0.000
#>    .y6_2             72.254    8.353    8.650    0.000
#>    .y6_3             91.610   10.487    8.736    0.000
#>    .y6_4             22.022    4.032    5.462    0.000
#>     t1f1              1.000                           
#>     t6f1              4.240    0.546    7.759    0.000
strong_fit <- Strong(
  data = df,
  time_points = time_points,
  factor_loadings = factor_loadings,
  mimic = "mplus"
)
lavaan::summary(strong_fit)
#> lavaan 0.6.16 ended normally after 52 iterations
#> 
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        27
#>   Number of equality constraints                     8
#> 
#>   Number of observations                           204
#>   Number of missing patterns                         1
#> 
#> Model Test User Model:
#>                                                       
#>   Test statistic                                53.723
#>   Degrees of freedom                                25
#>   P-value (Chi-square)                           0.001
#> 
#> Parameter Estimates:
#> 
#>   Standard errors                             Standard
#>   Information                                 Observed
#>   Observed information based on                Hessian
#> 
#> Latent Variables:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 =~                                             
#>     y1_1     (l11)    5.270    0.331   15.917    0.000
#>     y1_2     (l12)    4.525    0.312   14.487    0.000
#>     y1_3     (l13)    4.960    0.328   15.112    0.000
#>     y1_4     (l14)    4.547    0.291   15.634    0.000
#>   t6f1 =~                                             
#>     y6_1     (l11)    5.270    0.331   15.917    0.000
#>     y6_2     (l12)    4.525    0.312   14.487    0.000
#>     y6_3     (l13)    4.960    0.328   15.112    0.000
#>     y6_4     (l14)    4.547    0.291   15.634    0.000
#> 
#> Covariances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 ~~                                             
#>     t6f1              1.608    0.142   11.316    0.000
#> 
#> Intercepts:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1      (i1)   19.929    0.457   43.623    0.000
#>    .y1_2      (i2)   21.459    0.598   35.901    0.000
#>    .y1_3      (i3)   14.882    0.529   28.146    0.000
#>    .y1_4      (i4)   20.311    0.421   48.252    0.000
#>    .y6_1      (i1)   19.929    0.457   43.623    0.000
#>    .y6_2      (i2)   21.459    0.598   35.901    0.000
#>    .y6_3      (i3)   14.882    0.529   28.146    0.000
#>    .y6_4      (i4)   20.311    0.421   48.252    0.000
#>     t1f1              0.000                           
#>     t6f1              5.337    0.354   15.077    0.000
#> 
#> Variances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1             15.124    2.238    6.757    0.000
#>    .y1_2             57.819    6.150    9.402    0.000
#>    .y1_3             34.209    3.869    8.841    0.000
#>    .y1_4             16.339    2.114    7.729    0.000
#>    .y6_1             45.360    6.338    7.157    0.000
#>    .y6_2             74.229    8.352    8.887    0.000
#>    .y6_3             89.572   10.110    8.860    0.000
#>    .y6_4             24.586    3.951    6.223    0.000
#>     t1f1              1.000                           
#>     t6f1              4.557    0.585    7.791    0.000
strict_fit <- Strict(
  data = df,
  time_points = time_points,
  factor_loadings = factor_loadings,
  mimic = "mplus"
)
lavaan::summary(strict_fit)
#> lavaan 0.6.16 ended normally after 57 iterations
#> 
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        27
#>   Number of equality constraints                    12
#> 
#>   Number of observations                           204
#>   Number of missing patterns                         1
#> 
#> Model Test User Model:
#>                                                       
#>   Test statistic                               134.559
#>   Degrees of freedom                                29
#>   P-value (Chi-square)                           0.000
#> 
#> Parameter Estimates:
#> 
#>   Standard errors                             Standard
#>   Information                                 Observed
#>   Observed information based on                Hessian
#> 
#> Latent Variables:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 =~                                             
#>     y1_1     (l11)    5.083    0.364   13.978    0.000
#>     y1_2     (l12)    4.309    0.333   12.944    0.000
#>     y1_3     (l13)    4.785    0.356   13.447    0.000
#>     y1_4     (l14)    4.358    0.317   13.765    0.000
#>   t6f1 =~                                             
#>     y6_1     (l11)    5.083    0.364   13.978    0.000
#>     y6_2     (l12)    4.309    0.333   12.944    0.000
#>     y6_3     (l13)    4.785    0.356   13.447    0.000
#>     y6_4     (l14)    4.358    0.317   13.765    0.000
#> 
#> Covariances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>   t1f1 ~~                                             
#>     t6f1              1.812    0.168   10.812    0.000
#> 
#> Intercepts:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1      (i1)   20.019    0.509   39.339    0.000
#>    .y1_2      (i2)   21.513    0.621   34.648    0.000
#>    .y1_3      (i3)   14.805    0.617   23.988    0.000
#>    .y1_4      (i4)   20.313    0.433   46.915    0.000
#>    .y6_1      (i1)   20.019    0.509   39.339    0.000
#>    .y6_2      (i2)   21.513    0.621   34.648    0.000
#>    .y6_3      (i3)   14.805    0.617   23.988    0.000
#>    .y6_4      (i4)   20.313    0.433   46.915    0.000
#>     t1f1              0.000                           
#>     t6f1              5.557    0.415   13.396    0.000
#> 
#> Variances:
#>                    Estimate  Std.Err  z-value  P(>|z|)
#>    .y1_1      (u1)   28.657    2.958    9.689    0.000
#>    .y1_2      (u2)   68.013    5.253   12.946    0.000
#>    .y1_3      (u3)   61.387    4.897   12.535    0.000
#>    .y1_4      (u4)   20.878    2.142    9.746    0.000
#>    .y6_1      (u1)   28.657    2.958    9.689    0.000
#>    .y6_2      (u2)   68.013    5.253   12.946    0.000
#>    .y6_3      (u3)   61.387    4.897   12.535    0.000
#>    .y6_4      (u4)   20.878    2.142    9.746    0.000
#>     t1f1              1.000                           
#>     t6f1              5.056    0.692    7.304    0.000
```

### Model Comparisons


```r
mi <- Comparison(
  configural = configural_fit,
  weak = weak_fit,
  strong = strong_fit,
  strict = strict_fit
)
```

PERHAPS WE CAN MAKE METHODS TO SIMPLIFY THE OUTPUT.


```r
mi$fit_measures
#>                                 configural          weak        strong
#> npar                          2.500000e+01  2.200000e+01  1.900000e+01
#> fmin                          6.364765e-02  1.026893e-01  1.316735e-01
#> chisq                         2.596824e+01  4.189725e+01  5.372281e+01
#> df                            1.900000e+01  2.200000e+01  2.500000e+01
#> pvalue                        1.310764e-01  6.432407e-03  7.216997e-04
#> baseline.chisq                8.477405e+02  8.477405e+02  8.477405e+02
#> baseline.df                   2.800000e+01  2.800000e+01  2.800000e+01
#> baseline.pvalue               0.000000e+00  0.000000e+00  0.000000e+00
#> cfi                           9.914995e-01  9.757274e-01  9.649611e-01
#> tli                           9.874729e-01  9.691076e-01  9.607564e-01
#> cfi.robust                    9.914995e-01  9.757274e-01  9.649611e-01
#> tli.robust                    9.874729e-01  9.691076e-01  9.607564e-01
#> nnfi                          9.874729e-01  9.691076e-01  9.607564e-01
#> rfi                           9.548577e-01  9.370989e-01  9.290236e-01
#> nfi                           9.693677e-01  9.505777e-01  9.366282e-01
#> pnfi                          6.577852e-01  7.468825e-01  8.362752e-01
#> ifi                           9.915918e-01  9.759037e-01  9.650889e-01
#> rni                           9.914995e-01  9.757274e-01  9.649611e-01
#> nnfi.robust                   9.874729e-01  9.691076e-01  9.607564e-01
#> rni.robust                    9.914995e-01  9.757274e-01  9.649611e-01
#> logl                         -5.601115e+03 -5.609079e+03 -5.614992e+03
#> unrestricted.logl            -5.588131e+03 -5.588131e+03 -5.588131e+03
#> aic                           1.125223e+04  1.126216e+04  1.126798e+04
#> bic                           1.133518e+04  1.133516e+04  1.133103e+04
#> ntotal                        2.040000e+02  2.040000e+02  2.040000e+02
#> bic2                          1.125597e+04  1.126545e+04  1.127083e+04
#> rmsea                         4.240037e-02  6.658404e-02  7.504614e-02
#> rmsea.ci.lower                0.000000e+00  3.464774e-02  4.720491e-02
#> rmsea.ci.upper                7.945826e-02  9.696861e-02  1.027290e-01
#> rmsea.ci.level                9.000000e-01  9.000000e-01  9.000000e-01
#> rmsea.pvalue                  5.882580e-01  1.734975e-01  6.712191e-02
#> rmsea.close.h0                5.000000e-02  5.000000e-02  5.000000e-02
#> rmsea.notclose.pvalue         4.718752e-02  2.532922e-01  4.095424e-01
#> rmsea.notclose.h0             8.000000e-02  8.000000e-02  8.000000e-02
#> rmsea.robust                  4.240037e-02  6.658404e-02  7.504614e-02
#> rmsea.ci.lower.robust         0.000000e+00  3.464774e-02  4.720491e-02
#> rmsea.ci.upper.robust         7.945826e-02  9.696861e-02  1.027290e-01
#> rmsea.pvalue.robust           5.882580e-01  1.734975e-01  6.712191e-02
#> rmsea.notclose.pvalue.robust  4.718752e-02  2.532922e-01  4.095424e-01
#> rmr                           2.859752e+00  7.496699e+00  7.600600e+00
#> rmr_nomean                    3.161575e+00  8.287912e+00  8.401847e+00
#> srmr                          3.064127e-02  7.629877e-02  8.718366e-02
#> srmr_bentler                  3.064126e-02  7.202174e-02  8.589969e-02
#> srmr_bentler_nomean           3.387519e-02  7.962303e-02  9.429007e-02
#> crmr                          3.387520e-02  5.370899e-02  6.853573e-02
#> crmr_nomean                   3.841087e-02  6.090027e-02  7.664719e-02
#> srmr_mplus                    3.064127e-02  7.629877e-02  8.718366e-02
#> srmr_mplus_nomean             3.387520e-02  6.520903e-02  7.931397e-02
#> cn_05                         2.378000e+02  1.661799e+02  1.439766e+02
#> cn_01                         2.853064e+02  1.971711e+02  1.692726e+02
#> gfi                           9.946870e-01  9.913395e-01  9.890256e-01
#> agfi                          9.876963e-01  9.826790e-01  9.806851e-01
#> pgfi                          4.295239e-01  4.956698e-01  5.619464e-01
#> mfi                           9.830660e-01  9.524023e-01  9.320218e-01
#> ecvi                          3.723933e-01  4.210650e-01  4.496216e-01
#>                                     strict
#> npar                          1.500000e+01
#> fmin                          3.298018e-01
#> chisq                         1.345591e+02
#> df                            2.900000e+01
#> pvalue                        1.554312e-15
#> baseline.chisq                8.477405e+02
#> baseline.df                   2.800000e+01
#> baseline.pvalue               0.000000e+00
#> cfi                           8.712286e-01
#> tli                           8.756690e-01
#> cfi.robust                    8.712286e-01
#> tli.robust                    8.756690e-01
#> nnfi                          8.756690e-01
#> rfi                                     NA
#> nfi                                     NA
#> pnfi                          8.713187e-01
#> ifi                           8.710713e-01
#> rni                           8.712286e-01
#> nnfi.robust                   8.756690e-01
#> rni.robust                    8.712286e-01
#> logl                         -5.655410e+03
#> unrestricted.logl            -5.588131e+03
#> aic                           1.134082e+04
#> bic                           1.139059e+04
#> ntotal                        2.040000e+02
#> bic2                          1.134307e+04
#> rmsea                         1.335777e-01
#> rmsea.ci.lower                1.112465e-01
#> rmsea.ci.upper                1.567971e-01
#> rmsea.ci.level                9.000000e-01
#> rmsea.pvalue                  3.567812e-09
#> rmsea.close.h0                5.000000e-02
#> rmsea.notclose.pvalue         9.999344e-01
#> rmsea.notclose.h0             8.000000e-02
#> rmsea.robust                  1.335777e-01
#> rmsea.ci.lower.robust         1.112465e-01
#> rmsea.ci.upper.robust         1.567971e-01
#> rmsea.pvalue.robust           3.567812e-09
#> rmsea.notclose.pvalue.robust  9.999344e-01
#> rmr                           1.006330e+01
#> rmr_nomean                    1.112501e+01
#> srmr                          1.690386e-01
#> srmr_bentler                  1.328427e-01
#> srmr_bentler_nomean           1.465099e-01
#> crmr                          8.865701e-02
#> crmr_nomean                   9.986277e-02
#> srmr_mplus                    1.690386e-01
#> srmr_mplus_nomean             1.452372e-01
#> cn_05                         6.551901e+01
#> cn_01                         7.617832e+01
#> gfi                           9.759012e-01
#> agfi                          9.634363e-01
#> pgfi                          6.432076e-01
#> mfi                           7.720366e-01
#> ecvi                          8.066624e-01
```


```r
mi$difference
#> $`configural against weak`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)   
#> configural 19 11252 11335 25.968                                         
#> weak       22 11262 11335 41.897     15.929 0.14535       3   0.001173 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`configural against strong`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> configural 19 11252 11335 25.968                                          
#> strong     25 11268 11331 53.723     27.755 0.13332       6  0.0001045 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`configural against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>            Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> configural 19 11252 11335  25.968                                          
#> strict     29 11341 11391 134.559     108.59 0.21984      10  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`weak against strong`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)   
#> weak   22 11262 11335 41.897                                         
#> strong 25 11268 11331 53.723     11.826 0.12009       3   0.008005 **
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`weak against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> weak   22 11262 11335  41.897                                          
#> strict 29 11341 11391 134.559     92.662 0.24492       7  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> $`strong against strict`
#> 
#> Chi-Squared Difference Test
#> 
#>        Df   AIC   BIC   Chisq Chisq diff   RMSEA Df diff Pr(>Chisq)    
#> strong 25 11268 11331  53.723                                          
#> strict 29 11341 11391 134.559     80.836 0.30686       4  < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

## References
